### ISSUE TITLE
Vagrantfile error

### ISSUE THREAD

**Issue by funnelfiasco** [fedora-infra/tiny-stage#32]
I just installed tiny-stage and got this error running `vagrant up`

~~~~
Vagrant failed to initialize at a very early stage:

There is a syntax error in the following Vagrantfile. The syntax error
message is reproduced below for convenience:

/home/bcotton/devel/tiny-stage/Vagrantfile:70: syntax error, unexpected .., expecting ']'
          prop_elems[..-2].each do |elem_prop|
                       ^
~~~~

This is on F34 with ruby 3.0.1p64

**Comment by ryanlerch** [comment]
Okay, this is a super strange one -- i'm running F34, with the same ruby - and it all works for me. 

not sure why ruby is throwing a syntax error for you there...

i also got @nphilipp to check on his machine too, and it works for him as well...

**Comment by ryanlerch** [comment]
Could it be possible that for some reason you have two versions of Ruby installed? (not sure how this could happen)

The syntax that you are getting the error for was introduced in 2.7.0 of ruby, on Dec 25, 2019 -- so a whiles back, but not too far back.

Maybe try temporarily removing that line from the Vagrantfile, and getting Vagrant to output the ruby version  it is using with this line at the top of the Vagrantfile?

```
print "ruby #{ RUBY_VERSION }p#{ RUBY_PATCHLEVEL }"
```

**Comment by funnelfiasco** [comment]
Well that was an adventure. Turns out I had an old version of vagrant from the Red Hat CSB repo. It had a very old embedded ruby, which is what vagrant uses. I updated to the version in the Fedora repo and  it works.
