### ISSUE TITLE
Update past F36

### ISSUE THREAD

**Issue by AdamWill** [fedora-infra/tiny-stage#45]
I just ran this thing for the first time as part of trying to get a Bodhi dev instance up, and it's downloading F36 images:

    [adamw@xps13a tiny-stage (main)]$ vagrant up
    Bringing machine 'freeipa' up with 'libvirt' provider...
    Bringing machine 'fasjson' up with 'libvirt' provider...
    Bringing machine 'ipsilon' up with 'libvirt' provider...
    Bringing machine 'tinystage' up with 'libvirt' provider...
    ==> freeipa: Box 'f36-cloud-libvirt' could not be found. Attempting to find and install...
        freeipa: Box Provider: libvirt
        freeipa: Box Version: >= 0
    ==> freeipa: Box file was not detected as metadata. Adding it directly...
    ==> freeipa: Adding box 'f36-cloud-libvirt' (v0) for provider: libvirt
        freeipa: Downloading: https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-36-1.5.x86_64.vagrant-libvirt.box

it probably shouldn't be doing that any more...

**Comment by abompard** [comment]
Fixed by c2ed51deabb8bfaeca41f8709e167569d85dd31d, thanks.
