### ISSUE TITLE
Vagrant up failing on ipsilon initialization

### ISSUE THREAD

**Issue by mattiaverga** [fedora-infra/tiny-stage#46]
https://github.com/fedora-infra/tiny-stage/blob/c2ed51deabb8bfaeca41f8709e167569d85dd31d/ansible/roles/ipsilon/tasks/main.yml#L52

Shouldn't this be
`failed_when: '" already exists" in result.stderr or result.rc != 0' `
?

**Comment by abompard** [comment]
I don't want the task to be marked as failed when there's `already exsists` in the output, but the `result.rc` check is wrong indeed! Thanks.
@ryanlerch  you were looking at that as well

**Comment by ryanlerch** [comment]
i'll can fix this one -- but just need to get auth provisioning working from scratch to test the already exists case here.

hitting a couple other issues with bringing up the auth box.

**Comment by abompard** [comment]
Looks like I didn't test it enough before pushing the commit, sorry about that.
